# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Boilr Jekyll
description: >- # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec odio orci,
  rhoncus sodales est quis, mollis iaculis ante. Etiam faucibus maximus odio, ac
  ultricies mauris malesuada et.
baseurl: 'christmas-gift' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
source: src/jekyll
destination: dist
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
keep_files:
  - assets
  - css
  - fonts
  - img
  - js
  - svg

# Disable caching of content to disk in order to skip creating a .jekyll-cache or
# similar directory at the source to avoid interference with virtual environments
# and third-party directory watchers. Caching to disk is always disabled in safe mode.
disable_disk_cache: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# overrides your excluded items configuration and the default include array ([".htaccess"])
include:
  - .htaccess
